INSERT INTO usuario(nombreUsuario, numero_telefono, correo, equipo_favorito, nick_name, contraseña) VALUES ('Juan Lopez', '62326742', 'ju@ja.ji', 'Dallas Mavericks', 'juanito32', 'string123');
INSERT INTO usuario(nombreUsuario, numero_telefono, correo, equipo_favorito, nick_name, contraseña) VALUES ('Eduardo Pizarro', '648068282', 'edupriv2002@gmail.com', 'Chicago Bulls', 'pizarrock', 'string123');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('1', 'Boston Celtics', 'Boston', 'Este', 'Atlantico', '1946', '78', '17', '22', '62', '16', '0.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('2', 'Brooklyn Nets', 'New York', 'Este', 'Atlantico', '1967', '57', '0', '2', '31', '48', '31.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('3', 'New York Knicks', 'New York', 'Este', 'Atlantico', '1946', '78', '2', '8', '46', '32', '16.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('4', 'Philadelphia 76ers', 'Filadelfia', 'Este', 'Atlantico', '1939', '78', '3', '9', '44', '35', '18.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('5', 'Toronto Raptors', 'Toronto', 'Este', 'Atlantico', '1994', '1946', '78', '1', '1', '25', '53', '37.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('6', 'Chicago Bulls', 'Chicago', 'Este', 'Central', '1966', '58', '6', '6', '37', '41', '25.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('7', 'Cleveland Cavaliers', 'Cleveland', 'Este', 'Central', '1970', '54', '1', '5', '46', '33', '16.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('8', 'Detroit Pistons', 'Detroit', 'Este', 'Central', '1941', '78', '3', '5', '13', '65', '49.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('9', 'Indiana Pacers', 'Indianapolis', 'Este', 'Central', '1967', '57', '0', '1', '45', '34', '17.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('10', 'Milwaukee Bucks', 'Milwaukee', 'Este', 'Central', '1968', '56', '2', '3', '47', '31', '15.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('11', 'Atlanta Hawks', 'Atlanta', 'Este', 'Sureste', '1946', '78', '1', '1', '36', '42', '26.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('12', 'Charlotte Hornets', 'Charlotte', 'Este', 'Sureste', '1988', '36', '0', '0', '19', '59', '43.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('13', 'Miami Heat', 'Miami', 'Este', 'Sureste', '1988', '36', '3', '7', '43', '35', '19.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('14', 'Orlando Magic', 'Orlando', 'Este', 'Sureste', '1989', '35', '0', '2', '46', '32', '16.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('15', 'Washington Wizards', 'Washington D.C.', 'Este', 'Sureste', '1961', '63', '1', '4', '15', '64', '47.5', 'http');



INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('16', 'Denver Nuggets', 'Denver', 'Oeste', 'Noroeste', '1967', '57', '1', '1', '54', '24', '0.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('17', 'Minnesota Timberwolves', 'Mineapolis', 'Oeste', 'Noroeste', '1989', '35', '0', '0', '54', '24', '0.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('18', 'Oklahoma City Thunder', 'Oklahoma City', 'Oeste', 'Noroeste', '2008', '16', '0', '1', '53', '25', '1.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('19', 'Portland Trail Blazers', 'Portland', 'Oeste', 'Noroeste', '1970', '54', '1', '3', '21', '57', '33.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('20', 'Utah Jazz', 'Salt Lake', 'Oeste', 'Noroeste', '1974', '50', '0', '2', '29', '49', '25.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('21', 'Golden State Warriors', 'San Francisco', 'Oeste', 'Pacifico', '1946', '78', '7', '9', '43', '35', '11.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('22', 'Los Angeles Clippers', 'Los Angeles', 'Oeste', 'Pacifico', '1970', '54', '0', '0', '50', '28', '4.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('23', 'Los Angeles Lakers', 'Los Angeles', 'Oeste', 'Pacifico', '1947', '77', '17', '32', '45', '34', '9.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('24', 'Phoenix Suns', 'Phoenix ', 'Oeste', 'Pacifico', '1968', '56', '0', '3', '46', '32', '8.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('25', 'Sacramento Kings', 'Sacramento', 'Oeste', 'Pacifico', '1923', '78', '1', '1', '45', '33', '9.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('26', 'Dallas Mavericks', 'Dallas', 'Oeste', 'Suroeste', '1980', '44', '1', '2', '48', '30', '6.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('27', 'Houston Rockets', 'Houston', 'Oeste', 'Suroeste', '1967', '57', '2', '4', '38', '40', '16.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('28', 'Memphis Grizzlies', 'Memphis', 'Oeste', 'Suroeste', '1995', '29', '0', '0', '27', '51', '27.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('29', 'New Orleans Pelicans', 'New Orleans', 'Oeste', 'Suroeste', '2002', '22', '0', '0', '46', '32', '8.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('30', 'San Antonio Spurs', 'San Antonio', 'Oeste', 'Suroeste', '1967', '57', '5', '6', '19', '59', '35.0', 'http');



INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('1', 'LeBron James', 'Alero', '6', 'Cleveland Cavaliers (2003-2010), Miami Heat (2010-2014), Cleveland Cavaliers (2014-2018), Los Angeles Lakers (2018-2024)', '2003', '40', '17', '18', '0', 'http', '1');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('2', 'Kevin Durant', 'Alero', '7', 'Seattle SuperSonics (2007-2008), Oklahoma City Thunder (2008-2016), Golden State Warriors (2016-2019), Brooklyn Nets (2019-2022), Phoenix Suns (2022-2024)', '2007', '33', '11', '14', '0', 'http', '2');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('3', 'Stephen Curry', 'Base', '30', 'Golden State Warriors (2009-2024)', '2009', '35', '7', '13', '0', 'http', '3');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('4', 'Kawhi Leonard', 'Alero', '2', 'San Antonio Spurs (2011-2018), Toronto Raptors (2018-2019), Los Angeles Clippers (2019-2024)', '2011', '30', '5', '10', '0', 'http', '4');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('5', 'Giannis Antetokounmpo', 'Alero', '34', 'Milwaukee Bucks (2013-2024)', '2013', '29', '6', '9', '0', 'http', '5');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('6', 'Anthony Davis', 'Pivot', '3', 'New Orleans Pelicans (2012-2019), Los Angeles Lakers (2019-2024)', '2012', '29', '8', '9', '0', 'http', '6');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('7', 'James Harden', 'Escolta', '13', 'Oklahoma City Thunder (2009-2012), Houston Rockets (2012-2021), Brooklyn Nets (2021-2022), Philadelphia 76ers (2022-2023), Los Angeles Clippers (2023-2024)', '2009', '33', '9', '13', '0', 'http', '7');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('8', 'Luka Doncic', 'Base', '77', 'Dallas Mavericks (2018-2024)', '2018', '23', '3', '6', '0', 'http', '8');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('9', 'Damian Lillard', 'Base', '0', 'Portland Trail Blazers (2012-2023), Milwaukee Bucks (2023-2024)', '2012', '32', '6', '9', '0', 'http', '9');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('10', 'Nikola Jokic', 'Pivot', '15', 'Denver Nuggets (2015-2024)', '2015', '29', '4', '7', '0', 'http', '10');

INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('1', '35000', '9000', '10000', '1000', '2000', '1500', '1000', '500', '1000', '2000', '3000', '40000', '4', '2', '6', '2');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('2', '30000', '8000', '9000', '800', '1500', '1200', '800', '400', '800', '1500', '2500', '30000', '2', '1', '3', '1');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('3', '25000', '7000', '8000', '700', '1000', '1000', '700', '300', '700', '1000', '2000', '20000', '1', '0', '2', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('4', '20000', '6000', '7000', '600', '800', '800', '600', '200', '600', '800', '1500', '15000', '0', '1', '1', '2');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('5', '15000', '5000', '6000', '500', '600', '600', '500', '100', '500', '600', '1000', '10000', '0', '0', '0', '1');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('6', '10000', '4000', '5000', '400', '400', '400', '300', '100', '400', '400', '800', '5000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('7', '8000', '3000', '4000', '300', '300', '300', '200', '100', '300', '300', '600', '3000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('8', '6000', '2000', '3000', '200', '200', '200', '100', '100', '200', '200', '400', '2000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('9', '4000', '1000', '2000', '100', '100', '100', '50', '50', '100', '100', '200', '1000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('10', '2000', '500', '1000', '50', '50', '50', '25', '25', '50', '50', '100', '500', '0', '0', '0', '0');



INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('1', 'Gregg Popovich', 'San Antonio Spurs','San Antonio Spurs (1996-2024)', '70', '28', '0', '0', 'false', 'http', '1');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('2', 'Steve Kerr', 'Golden State Warriors (2014-2024)', '60', '10', '0', '0', 'true', 'http', '2');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('3', 'Erik Spoelstra', 'Miami Heat (2008-2024)', '50', '16', '0', '0', 'false', 'http', '3');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('4', 'Tyronn Lue', 'Los Angeles Clippers (2020-2024)', '45', '4', '0', '0', 'true', 'http', '4');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('5', 'Frank Vogel', 'Los Angeles Lakers (2019-2024)', '45', '5', '0', '0', 'false', 'http', '5');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('6', 'Mike Budenholzer', 'Milwaukee Bucks (2018-2024)', '50', '6', '0', '0', 'false', 'http', '6');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('7', 'Doc Rivers', 'Philadelphia 76ers (2019-2024)', '60', '5', '0', '0', 'true', 'http', '7');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('8', 'Quin Snyder', 'Utah Jazz (2014-2024)', '50', '10', '0', '0', 'false', 'http', '8');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('9', 'Nick Nurse', 'Toronto Raptors (2018-2024)', '50', '6', '0', '0', 'false', 'http', '9');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('10', 'Rick Carlisle', 'Indiana Pacers (2003-2007), Dallas Mavericks (2008-2024)', '60', '21', '0', '0', 'true', 'http', '10');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('11', 'Tom Thibodeau', 'Chicago Bulls (2010-2015), Minnesota Timberwolves (2016-2019), New York Knicks (2020-2024)', '60', '14', '0', '0', 'false', 'http', '11');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('12', 'Steve Clifford', 'Charlotte Hornets (2013-2018), Orlando Magic (2018-2024)', '60', '11', '0', '0', 'false', 'http', '12');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('13', 'Lloyd Pierce', 'Atlanta Hawks (2018-2021), Philadelphia 76ers (2021-2024)', '50', '6', '0', '0', 'false', 'http', '13');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('14', 'James Borrego', 'San Antonio Spurs (2003-2010), New Orleans Hornets (2010-2012), Orlando Magic (2012-2018), Charlotte Hornets (2018-2024)', '50', '21', '0', '0', 'false', 'http', '14');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('15', 'Nate McMillan', 'Seattle SuperSonics (2000-2005), Portland Trail Blazers (2005-2012), Indiana Pacers (2016-2021), Atlanta Hawks (2021-2024)', '60', '14', '0', '0', 'true', 'http', '15');

INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('16', 'Michael Malone', 'Sacramento Kings (2013-2015), Denver Nuggets (2015-2024)', '50', '11', '0', '0', 'false', 'http', '16');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('17', 'Ryan Saunders', 'Minnesota Timberwolves (2019-2021)', '40', '2', '0', '0', 'false', 'http', '17');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('18', 'Billy Donovan', 'Oklahoma City Thunder (2015-2020), Chicago Bulls (2020-2024)', '50', '9', '0', '0', 'true', 'http', '18');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('19', 'Terry Stotts', 'Atlanta Hawks (2002-2004), Milwaukee Bucks (2005-2007), Portland Trail Blazers (2012-2024)', '60', '19', '0', '0', 'false', 'http', '19');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('20', 'Quin Snyder', 'Utah Jazz (2014-2024)', '50', '10', '0', '0', 'false', 'http', '20');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('21', 'Steve Kerr', 'Golden State Warriors (2014-2024)', '60', '10', '0', '0', 'true', 'http', '21');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('22', 'Doc Rivers', 'Philadelphia 76ers (2019-2024)', '60', '5', '0', '0', 'true', 'http', '22');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('23', 'Rick Carlisle', 'Indiana Pacers (2003-2007), Dallas Mavericks (2008-2024)', '60', '21', '0', '0', 'true', 'http', '23');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('24', 'Tom Thibodeau', 'Chicago Bulls (2010-2015), Minnesota Timberwolves (2016-2019), New York Knicks (2020-2024)', '60', '14', '0', '0', 'false', 'http', '24');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('25', 'Steve Clifford', 'Charlotte Hornets (2013-2018), Orlando Magic (2018-2024)', '60', '11', '0', '0', 'false', 'http', '25');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('26', 'Lloyd Pierce', 'Atlanta Hawks (2018-2021), Philadelphia 76ers (2021-2024)', '50', '6', '0', '0', 'false', 'http', '26');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('27', 'James Borrego', 'San Antonio Spurs (2003-2010), New Orleans Hornets (2010-2012), Orlando Magic (2012-2018), Charlotte Hornets (2018-2024)', '50', '21', '0', '0', 'false', 'http', '27');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('28', 'Nate McMillan', 'Seattle SuperSonics (2000-2005), Portland Trail Blazers (2005-2012), Indiana Pacers (2016-2021), Atlanta Hawks (2021-2024)', '60', '14', '0', '0', 'true', 'http', '28');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('29', 'Michael Malone', 'Sacramento Kings (2013-2015), Denver Nuggets (2015-2024)', '50', '11', '0', '0', 'false', 'http', '29');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('30', 'Ryan Saunders', 'Minnesota Timberwolves (2019-2021)', '40', '2', '0', '0', 'false', 'http', '30');
