INSERT INTO usuario(nombre_usuario, contraseña, correo, equipo_favorito, foto, nick_name, numero_telefono) VALUES ('Juan Lopez', 'string123', 'ju@ja.ji', 'Dallas Mavericks', 'http', 'juanito32', '62326742');
INSERT INTO usuario(nombre_usuario, contraseña, correo, equipo_favorito, foto, nick_name, numero_telefono) VALUES ('Eduardo Pizarro', '648068282', 'edupriv2002@gmail.com', 'Chicago Bulls', 'http', 'pizarrock', 'string123');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('1', 'Boston Celtics', 'Boston', 'Este', 'Atlantico', '1946', '78', '17', '22', '62', '16', '0.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('2', 'Brooklyn Nets', 'New York', 'Este', 'Atlantico', '1967', '57', '0', '2', '31', '48', '31.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('3', 'New York Knicks', 'New York', 'Este', 'Atlantico', '1946', '78', '2', '8', '46', '32', '16.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('4', 'Philadelphia 76ers', 'Filadelfia', 'Este', 'Atlantico', '1939', '78', '3', '9', '44', '35', '18.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('5', 'Toronto Raptors', 'Toronto', 'Este', 'Atlantico', '1994', '1946', '78', '1', '1', '25', '53', '37.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('6', 'Chicago Bulls', 'Chicago', 'Este', 'Central', '1966', '58', '6', '6', '37', '41', '25.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('7', 'Cleveland Cavaliers', 'Cleveland', 'Este', 'Central', '1970', '54', '1', '5', '46', '33', '16.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('8', 'Detroit Pistons', 'Detroit', 'Este', 'Central', '1941', '78', '3', '5', '13', '65', '49.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('9', 'Indiana Pacers', 'Indianapolis', 'Este', 'Central', '1967', '57', '0', '1', '45', '34', '17.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('10', 'Milwaukee Bucks', 'Milwaukee', 'Este', 'Central', '1968', '56', '2', '3', '47', '31', '15.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('11', 'Atlanta Hawks', 'Atlanta', 'Este', 'Sureste', '1946', '78', '1', '1', '36', '42', '26.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('12', 'Charlotte Hornets', 'Charlotte', 'Este', 'Sureste', '1988', '36', '0', '0', '19', '59', '43.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('13', 'Miami Heat', 'Miami', 'Este', 'Sureste', '1988', '36', '3', '7', '43', '35', '19.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('14', 'Orlando Magic', 'Orlando', 'Este', 'Sureste', '1989', '35', '0', '2', '46', '32', '16.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('15', 'Washington Wizards', 'Washington D.C.', 'Este', 'Sureste', '1961', '63', '1', '4', '15', '64', '47.5', 'http');



INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('16', 'Denver Nuggets', 'Denver', 'Oeste', 'Noroeste', '1967', '57', '1', '1', '54', '24', '0.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('17', 'Minnesota Timberwolves', 'Mineapolis', 'Oeste', 'Noroeste', '1989', '35', '0', '0', '54', '24', '0.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('18', 'Oklahoma City Thunder', 'Oklahoma City', 'Oeste', 'Noroeste', '2008', '16', '0', '1', '53', '25', '1.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('19', 'Portland Trail Blazers', 'Portland', 'Oeste', 'Noroeste', '1970', '54', '1', '3', '21', '57', '33.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('20', 'Utah Jazz', 'Salt Lake', 'Oeste', 'Noroeste', '1974', '50', '0', '2', '29', '49', '25.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('21', 'Golden State Warriors', 'San Francisco', 'Oeste', 'Pacifico', '1946', '78', '7', '9', '43', '35', '11.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('22', 'Los Angeles Clippers', 'Los Angeles', 'Oeste', 'Pacifico', '1970', '54', '0', '0', '50', '28', '4.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('23', 'Los Angeles Lakers', 'Los Angeles', 'Oeste', 'Pacifico', '1947', '77', '17', '32', '45', '34', '9.5', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('24', 'Phoenix Suns', 'Phoenix ', 'Oeste', 'Pacifico', '1968', '56', '0', '3', '46', '32', '8.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('25', 'Sacramento Kings', 'Sacramento', 'Oeste', 'Pacifico', '1923', '78', '1', '1', '45', '33', '9.0', 'http');

INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('26', 'Dallas Mavericks', 'Dallas', 'Oeste', 'Suroeste', '1980', '44', '1', '2', '48', '30', '6.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('27', 'Houston Rockets', 'Houston', 'Oeste', 'Suroeste', '1967', '57', '2', '4', '38', '40', '16.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('28', 'Memphis Grizzlies', 'Memphis', 'Oeste', 'Suroeste', '1995', '29', '0', '0', '27', '51', '27.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('29', 'New Orleans Pelicans', 'New Orleans', 'Oeste', 'Suroeste', '2002', '22', '0', '0', '46', '32', '8.0', 'http');
INSERT INTO equipo(id_equipo, nombre_equipo, ciudad, conferencia, division, año_fundacion, años_nba, titulos_nba, titulos_conferencia, partidos_ganados, partidos_perdidos, balance_temporada, logo_equipo) VALUES ('30', 'San Antonio Spurs', 'San Antonio', 'Oeste', 'Suroeste', '1967', '57', '5', '6', '19', '59', '35.0', 'http');



INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('1', 'LeBron James', 'Alero', '6', 'Cleveland Cavaliers (2003-2010), Miami Heat (2010-2014), Cleveland Cavaliers (2014-2018), Los Angeles Lakers (2018-2024)', '2003', '40', '17', '18', '0', 'http', '1');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('2', 'Kevin Durant', 'Alero', '7', 'Seattle SuperSonics (2007-2008), Oklahoma City Thunder (2008-2016), Golden State Warriors (2016-2019), Brooklyn Nets (2019-2022), Phoenix Suns (2022-2024)', '2007', '33', '11', '14', '0', 'http', '2');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('3', 'Stephen Curry', 'Base', '30', 'Golden State Warriors (2009-2024)', '2009', '35', '7', '13', '0', 'http', '3');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('4', 'Kawhi Leonard', 'Alero', '2', 'San Antonio Spurs (2011-2018), Toronto Raptors (2018-2019), Los Angeles Clippers (2019-2024)', '2011', '30', '5', '10', '0', 'http', '4');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('5', 'Giannis Antetokounmpo', 'Alero', '34', 'Milwaukee Bucks (2013-2024)', '2013', '29', '6', '9', '0', 'http', '5');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('6', 'Anthony Davis', 'Pivot', '3', 'New Orleans Pelicans (2012-2019), Los Angeles Lakers (2019-2024)', '2012', '29', '8', '9', '0', 'http', '6');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('7', 'James Harden', 'Escolta', '13', 'Oklahoma City Thunder (2009-2012), Houston Rockets (2012-2021), Brooklyn Nets (2021-2022), Philadelphia 76ers (2022-2023), Los Angeles Clippers (2023-2024)', '2009', '33', '9', '13', '0', 'http', '7');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('8', 'Luka Doncic', 'Base', '77', 'Dallas Mavericks (2018-2024)', '2018', '23', '3', '6', '0', 'http', '8');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('9', 'Damian Lillard', 'Base', '0', 'Portland Trail Blazers (2012-2023), Milwaukee Bucks (2023-2024)', '2012', '32', '6', '9', '0', 'http', '9');
INSERT INTO jugador(id_jugador, nombre_jugador, posicion, dorsal, trayectoria_jug, año_draft, edad_jug, años_all_star_jug, años_nba_jug, años_otra_liga_jug, foto_jugador, id_est_jugador) VALUES ('10', 'Nikola Jokic', 'Pivot', '15', 'Denver Nuggets (2015-2024)', '2015', '29', '4', '7', '0', 'http', '10');

INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('1', '35000', '9000', '10000', '1000', '2000', '1500', '1000', '500', '1000', '2000', '3000', '40000', '4', '2', '6', '2');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('2', '30000', '8000', '9000', '800', '1500', '1200', '800', '400', '800', '1500', '2500', '30000', '2', '1', '3', '1');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('3', '25000', '7000', '8000', '700', '1000', '1000', '700', '300', '700', '1000', '2000', '20000', '1', '0', '2', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('4', '20000', '6000', '7000', '600', '800', '800', '600', '200', '600', '800', '1500', '15000', '0', '1', '1', '2');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('5', '15000', '5000', '6000', '500', '600', '600', '500', '100', '500', '600', '1000', '10000', '0', '0', '0', '1');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('6', '10000', '4000', '5000', '400', '400', '400', '300', '100', '400', '400', '800', '5000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('7', '8000', '3000', '4000', '300', '300', '300', '200', '100', '300', '300', '600', '3000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('8', '6000', '2000', '3000', '200', '200', '200', '100', '100', '200', '200', '400', '2000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('9', '4000', '1000', '2000', '100', '100', '100', '50', '50', '100', '100', '200', '1000', '0', '0', '0', '0');
INSERT INTO estadisticas_jugador(id_est_jugador, puntos_totales, asistencias_totales, rebotes_totales, tapones_totales, robos_totales, partidos_jugados_jug, partidos_ganados_jug, partidos_perdidos_jug, triples_anotados, tiros_libres_anotados, tiros_de_campo_anotados, minutos_totales, titulos_ganado_nba_jug, titulos_perdidos_nba_jug, titulos_ganado_conferencia_jug, titulos_perdidos_conferencia_jug) VALUES ('10', '2000', '500', '1000', '50', '50', '50', '25', '25', '50', '50', '100', '500', '0', '0', '0', '0');



INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('1', 'Joe Mazzulla', 'Boston Celtics', 'Boston Celtics (2022-2024)', '70', '28', '0', '0', 'false', 'http', '1');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('2', 'Jacque Vaughn', 'Brooklyn Nets', 'Orlando Magic (2012-2015), Brooklyn Nets (2022-2024)', '60', '10', '0', '0', 'true', 'http', '2');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('3', 'Tom Thibodeau', 'New York Knicks', 'Chicago Bulls (2010-2015), Minnesota Timberwolves (2016-2019), New York Knicks (2020-2024), ', '50', '16', '0', '0', 'false', 'http', '3');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('4', 'Nick Nurse', 'Philadelphia 76ers', 'Toronto Raptors (2018-2023), Philadelphia 76ers (2023-2024)', '45', '4', '0', '0', 'true', 'http', '4');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('5', 'Darko Rajakovic', 'Toronto Raptors', 'Toronto Raptors (2023-2024)', '45', '5', '0', '0', 'false', 'http', '5');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('6', 'Billy Donovan', 'Chicago Bulls', 'Oklahoma City Thunder (2015-2020), Chicago Bulls (2020-2024)', '55', '6', '0', '0', 'true', 'http', '6');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('7', 'J. Bickerstaff', 'Cleveland Cavaliers', 'Memphis Grizzlies (2017-2019), Cleveland Cavaliers (2020-2024)', '60', '5', '0', '0', 'true', 'http', '7');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('8', 'Monty Williams', 'Detroit Pistons', 'New Orleans Pelicans (2010-2015), Oklahoma City Thunder (2015-2016), Phoenix Suns(2019-2023), Detroit Pistons (2023-2024)', '50', '10', '0', '0', 'false', 'http', '8');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('9', 'Rick Carlisle', 'Indiana Pacers', 'Detroit Pistons (2001-2003), Indiana Pacers (2003-2007), Dallas Mavericks(2008-2021), Indiana Pacers (2021-2024)', '50', '6', '0', '0', 'false', 'http', '9');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('10', 'Doc Rivers', 'Milwaukee Bucks', 'Orlando Magic (1999-2003), Boston Celtics (2004-2013), Los Angeles Clippers (2013-2020), Philadelphia 76ers (2020-2023), Milwaukee Bucks (2023-2024)', '60', '21', '0', '0', 'true', 'http', '10');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('11', 'Quin Snyder', 'Atlanta Hawks', 'Utah Jazz (2014-2022), Atlanta Hawks (2023-2024)', '60', '14', '0', '0', 'false', 'http', '11');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('12', 'Steve Clifford', 'Charlotte Hornets', 'Charlotte Hornets (2013-2018), Orlando Magic (2018-2021), Charlotte Hornets (2022-2024)', '60', '11', '0', '0', 'false', 'http', '12');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('13', 'Erik Spoelstra', 'Miami Heat', 'Miami Heat (2008-2024)', '50', '6', '0', '0', 'false', 'http', '13');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('14', 'Jamahl Mosley', 'Orlando Magic', 'Orlando Magic (2021-2024)', '50', '21', '0', '0', 'false', 'http', '14');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('15', 'Brian Keefe', 'Washington Wizards', 'Washington Wizards (2023-2024)', '60', '14', '0', '0', 'true', 'http', '15');

INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('16', 'Michael Malone', 'Denver Nuggets', 'Sacramento Kings (2013-2014), Denver Nuggets (2015-2024)', '50', '11', '0', '0', 'false', 'http', '16');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('17', 'Chris Finch', 'Minnesota Timberwolves', 'Minnesota Timberwolves (2021-2024)', '40', '2', '0', '0', 'false', 'http', '17');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('18', 'Mark Daigneault', 'Oklahoma City Thunder', 'Oklahoma City Thunder (2020-2024)', '50', '9', '0', '0', 'true', 'http', '18');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('19', 'C. Billups', 'Portland Trail Blazers', 'Portland Trail Blazers (2021-2024)', '60', '19', '0', '0', 'false', 'http', '19');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('20', 'Will Hardy', 'Utah Jazz', 'Utah Jazz (2022-2024)', '50', '10', '0', '0', 'false', 'http', '20');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('21', 'Steve Kerr', 'Golden State Warriors', 'Golden State Warriors (2014-2024)', '60', '10', '0', '0', 'true', 'http', '21');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('22', 'Tyronn Lue', 'Los Angeles Clippers', 'Cleveland Cavaliers (2016-2018), Los Angeles Clippers (2020-2024)', '60', '5', '0', '0', 'true', 'http', '22');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('23', 'Darvin Ham', 'Los Angeles Lakers', 'Los Angeles Lakers (2022-2024)', '60', '21', '0', '0', 'true', 'http', '23');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('24', 'Frank Vogel', 'Phoenix Suns', 'Indiana Pacers (2011-2016), Orlando Magic (2016-2018), Los Angeles Lakers (2019-2022), Phoenix Suns (2023-2024)', '60', '14', '0', '0', 'false', 'http', '24');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('25', 'Mike Brown', 'Sacramento Kings', 'Cleveland Cavaliers (2005-10), Los Angeles Lakers (2011-12), Cleveland Cavaliers (2013-14), Sacramento Kings (2022-2024)', '60', '11', '0', '0', 'false', 'http', '25');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('26', 'Jason Kidd', 'Dallas Mavericks', 'Brooklyn Nets (2013-2014), Milwaukee Bucks (2014-2018), Dallas Mavericks (2021-2024)', '50', '6', '0', '0', 'false', 'http', '26');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('27', 'Ime Udoka', 'Houston Rockets', 'Boston Celtics (2021-2023), Houston Rockets (2023-2024)', '50', '21', '0', '0', 'false', 'http', '27');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('28', 'Taylor Jenkins', 'Memphis Grizzlies', 'Memphis Grizzlies (2019-2024)', '60', '14', '0', '0', 'true', 'http', '28');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('29', 'Willie Green', 'New Orleans Pelicans', 'New Orleans Pelicans (2021-2024)', '50', '11', '0', '0', 'false', 'http', '29');
INSERT INTO entrenador(id_entrenador, nombe_entrenador, equipo_entr, trayectoria_entr, edad_entr, años_nba_entr, años_otras_ligas_entr, años_all_star_entr, a_sido_jugador, foto_entrenador, id_est_entrenador) VALUES ('30', 'Gregg Popovich', 'San Antonio Spurs', 'San Antonio Spurs (1996-2024)', '40', '2', '0', '0', 'false', 'http', '30');

INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('1', '1000', '600', '400', '1', '1', '2', '1');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('2', '800', '400', '400', '0', '1', '1', '2');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('3', '700', '300', '400', '0', '0', '0', '1');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('4', '600', '200', '400', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('5', '500', '100', '400', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('6', '400', '100', '300', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('7', '300', '50', '250', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('8', '200', '25', '175', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('9', '100', '10', '90', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('10', '50', '5', '45', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('11', '1000', '600', '400', '1', '1', '2', '1');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('12', '800', '400', '400', '0', '1', '1', '2');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('13', '700', '300', '400', '0', '0', '0', '1');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('14', '600', '200', '400', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('15', '500', '100', '400', '0', '0', '0', '0');

INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('16', '400', '100', '300', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('17', '300', '50', '250', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('18', '200', '25', '175', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('19', '100', '10', '90', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('20', '50', '5', '45', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('21', '1000', '600', '400', '1', '1', '2', '1');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('22', '800', '400', '400', '0', '1', '1', '2');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('23', '700', '300', '400', '0', '0', '0', '1');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('24', '600', '200', '400', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('25', '500', '100', '400', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('26', '400', '100', '300', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('27', '300', '50', '250', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('28', '200', '25', '175', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('29', '100', '10', '90', '0', '0', '0', '0');
INSERT INTO estadisticas_entrenador(id_est_entrenador, partidos_jugados_entr, partidos_ganados_entr, partidos_perdidos_entr, titulos_ganado_nba_entr, titulos_perdidos_nba_entr, titulos_ganado_conferencia_entr, titulos_perdidos_conferencia_entr) VALUES ('30', '50', '5', '45', '0', '0', '0', '0');


INSERT INTO transferencia(id_transferencia, precio, ronda_draft, fecha, equipo_origen, equipo_destino, info_ronda_draft) VALUES ('1', '1000000', '1', '2024-01-01', 'Boston Celtics', 'Brooklyn Nets', '1');
INSERT INTO transferencia(id_transferencia, precio, ronda_draft, fecha, equipo_origen, equipo_destino, info_ronda_draft) VALUES ('2', '2000000', '2', '2024-01-01', 'Brooklyn Nets', 'New York Knicks', '2');
INSERT INTO transferencia(id_transferencia, precio, ronda_draft, fecha, equipo_origen, equipo_destino, info_ronda_draft) VALUES ('3', '3000000', '3', '2024-01-01', 'New York Knicks', 'Philadelphia 76ers', '3');
INSERT INTO transferencia(id_transferencia, precio, ronda_draft, fecha, equipo_origen, equipo_destino, info_ronda_draft) VALUES ('4', '4000000', '4', '2024-01-01', 'Philadelphia 76ers', 'Toronto Raptors', '4');



INSERT INTO temporada(id_temporada, años_temporada, campeon_temporada, mvp_temporada, rookie_temporada, defensor_temporada, sexto_hombre_temporada, jugador_mas_mejorado_temporada, entrenador_temporada, campeon_oeste_temp, campeon_este_temp, campeon_nba_temp) VALUES ('1', '2011', 'Dallas Mavericks', 'Derrick Rose', 'Blake Griffin', 'Dwight Howard', 'Lamar Odom', 'Kevin Love', 'Tom Thibodeau', 'Dallas Mavericks', 'Miami Heat', 'Dallas Mavericks');
INSERT INTO temporada(id_temporada, años_temporada, campeon_temporada, mvp_temporada, rookie_temporada, defensor_temporada, sexto_hombre_temporada, jugador_mas_mejorado_temporada, entrenador_temporada, campeon_oeste_temp, campeon_este_temp, campeon_nba_temp) VALUES ('2', '1996', 'Chicago Bulls', 'Michael Jordan', 'Allen Iverson', 'Gary Payton', 'John Starks', 'Michael Jordan', 'Phil Jackson', 'Seattle SuperSonics', 'Chicago Bulls', 'Chicago Bulls');



INSERT INTO playoff(id_play_off, campeones_cuartos_oeste, campeones_semis_oeste, campeon_final_oeste, campeones_cuartos_este, campeones_semis_este, campeon_final_este, campeon_final_nba) VALUES ('1', '(Chicago Bulls, New York Knicks, Atlanta Hawks, Orlando Magic)', '(Chicago Bulls, Orlando Magic)', 'Chicago Bulls', '(Seattle SuperSonics, Houston Rockets, Utah Jazz, San Antonio Spurs)', '(Seattle SuperSonics, Utah Jazz)', 'Seattle SuperSonics', 'Chicago Bulls');
INSERT INTO playoff(id_play_off, campeones_cuartos_oeste, campeones_semis_oeste, campeon_final_oeste, campeones_cuartos_este, campeones_semis_este, campeon_final_este, campeon_final_nba) VALUES ('2', '(Dallas Mavericks, Los Angeles Lakers, Denver Nuggets, Utah Jazz)', '(Dallas Mavericks, Utah Jazz)', 'Dallas Mavericks', '(Miami Heat, Boston Celtics, Chicago Bulls, Indiana Pacers)', '(Miami Heat, Chicago Bulls)', 'Miami Heat', 'Dallas Mavericks');



INSERT INTO jornada(id_jornada, fecha_jornada, numero_partido, partido_cancelado) VALUES ('1', '2024-01-01', '1', 'false');
INSERT INTO jornada(id_jornada, fecha_jornada, numero_partido, partido_cancelado) VALUES ('2', '2024-01-01', '2', 'false');



INSERT INTO categoria(id_categoria, ganador, duracion_votacion, categotia_votacion, opciones_votacion) VALUES ('1', 'Michael Jordan', '1', 'Mejor jugador de la historia', 'Michael Jordan, LeBron James, Kobe Bryant, Magic Johnson, Larry Bird');
