spring.main.allow-circular-references=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.datasource.url=jdbc:h2:file:./src/main/resources/demodb;
spring.datasource.tomcat.connection-properties=useUnicode=true;characterEncoding=UTF-8;
spring.datasource.connectionProperties=useUnicode=true;characterEncoding=utf-8
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.jackson.serialization.fail-on-empty-beans=false


spring.jpa.defer-datasource-initialization=true 
spring.sql.init.data-locations=classpath:db/data.sql
spring.sql.init.encoding=UTF-8

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

server.error.path=/error
server.port = 8081
server.error.whitelabel.enabled=false
# Habilitar mapeos de recursos estáticos y servir todo desde /static
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/static/


spring.devtools.restart.exclude=./src/main/resources/demodb.mv.db,./src/main/resources/demodb.trace.db;

spring.main.allow-bean-definition-overriding=true

# Logging
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.file.name=app.log
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG

balldontlie.api-key=c23ce05e-4f8c-4ef7-89c8-5e92822fdb16

